# Generated by Django 2.2 on 2019-04-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
