# Generated by Django 2.2 on 2019-04-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techBlog', '0002_auto_20190408_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='picture',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.TextField(),
        ),
    ]
