# Generated by Django 2.2 on 2019-04-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techBlog', '0007_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='poster',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
